Change the `generate` code to check if a tensor, not specifically a torch.FloatTensor.
The very specific check prevents the DatasetGenerator from running on the GPU.

Before this change:

```
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)
```

This was due to the wav2vec being skipped, leading to the audio data being passed through. You could run this code on the CPU, but it takes much longer.

This allows moving the process to the GPU.